spring:
  application:
    name: startup

  datasource:
    url: jdbc:postgresql://localhost:5432/one_database?currentSchema=study_serializer&options=-c%20TimeZone=America/Sao_Paulo
    username: app_user
    password: '@Java198106'

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    show-sql: false

  flyway:
    enable: true

logging:
  root: WARN
  com.alexdev: INFO